# Generated by Django 4.2.4 on 2023-08-25 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Grip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "aspect",
                    models.CharField(
                        choices=[
                            ("Top Pin", "Top Pin"),
                            ("Bottom Pin", "Bottom Pin"),
                            ("Attacking Guard", "Attacking Guard"),
                            ("Playing Guard", "Playing Guard"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "grips",
                    models.ManyToManyField(related_name="grips", to="techniques.grip"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Technique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "from_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_position",
                        to="techniques.position",
                    ),
                ),
                (
                    "to_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_position",
                        to="techniques.position",
                    ),
                ),
            ],
        ),
    ]
