# Generated by Django 4.2.4 on 2023-08-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("techniques", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="position",
            name="grips",
        ),
        migrations.AddField(
            model_name="position",
            name="their_grips",
            field=models.ManyToManyField(
                null=True, related_name="their_grips", to="techniques.grip"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="your_grips",
            field=models.ManyToManyField(
                null=True, related_name="your_grips", to="techniques.grip"
            ),
        ),
    ]
