# Generated by Django 4.2.4 on 2023-08-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("techniques", "0004_alter_position_aspect"),
    ]

    operations = [
        migrations.AddField(
            model_name="technique",
            name="notes",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
