# Generated by Django 4.2.4 on 2023-08-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("techniques", "0005_technique_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technique",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
