# Generated by Django 4.2.5 on 2023-09-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("techniques", "0009_alter_submissiontechnique_from_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True)),
                (
                    "positions",
                    models.ManyToManyField(blank=True, related_name="playlists", to="techniques.position"),
                ),
            ],
        ),
    ]
