# Generated by Django 4.2.4 on 2023-08-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("techniques", "0003_alter_position_their_grips_alter_position_your_grips"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="aspect",
            field=models.CharField(
                choices=[
                    ("Top", "Top Pin"),
                    ("Bottom", "Bottom Pin"),
                    ("Passing", "Attacking Guard"),
                    ("Playing", "Playing Guard"),
                    ("Submission", "Submission"),
                ],
                max_length=128,
            ),
        ),
    ]
