# Generated by Django 4.2.4 on 2023-09-05 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("techniques", "0006_alter_technique_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("notes", models.TextField(blank=True)),
                (
                    "from_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_from_position",
                        to="techniques.position",
                    ),
                ),
            ],
        ),
    ]
