# Generated by Django 4.2.4 on 2023-09-06 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("techniques", "0007_submissiontechnique"),
    ]

    operations = [
        migrations.AlterField(
            model_name="technique",
            name="from_position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="techniques_from",
                to="techniques.position",
            ),
        ),
        migrations.AlterField(
            model_name="technique",
            name="to_position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="techniques_to",
                to="techniques.position",
            ),
        ),
    ]
