# Generated by Django 4.2.4 on 2023-09-06 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("techniques", "0008_alter_technique_from_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submissiontechnique",
            name="from_position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions_from",
                to="techniques.position",
            ),
        ),
    ]
